name: CI

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt install -y clang-format

      - name: Run clang-format check
        run: |
          chmod +x ./checkFormat.sh
          ./checkFormat.sh

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake make g++ lcov

      - name: Clone and build GoogleTest
        run: |
          mkdir -p external
          cd external
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake -DCMAKE_INSTALL_PREFIX=/usr/local .
          make
          sudo make install

      - name: Run unit tests with coverage
        run: |
          chmod +x runTests.sh
          ./runTests.sh --coverage

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: test/coverage
